name: RcGacha
version: '${version}'
main: net.azisaba.rcgacha.RcGacha
description: Gacha plugin for rcpve
api-version: '1.21'
authors: [ sysnote8 ]
depend: [ RcItemLogging, MythicMobs ]
commands:
  rcgacha:
    permission: rcgacha.cmd.rcgacha